<?php

namespace TIC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use TIC\PlatformBundle\Entity\PerformancesTypes;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceTypeRepository extends EntityRepository
{
    /**
     * @return PerformancesTypes[]
     */
    public function findAllWithRequiredData()
    {
        $qb = $this->createQueryBuilder('pt');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $itemID
     * @return PerformancesTypes
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneWithRequiredData($itemID)
    {
        $qb = $this->createQueryBuilder('pt')
            ->where('pt.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $itemID
     * @return PerformancesTypes
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($itemID)
    {
        $qb = $this->createQueryBuilder('pt')
            ->leftJoin('pt.sessions', 's')
            ->addSelect('s')
            ->where('pt.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
