<?php

namespace TIC\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAllWithoutSuperAdmin()
    {
        $qb = $this->createQueryBuilder('u')
            ->where('NOT u.roles LIKE :role')
            ->setParameter('role', '%ROLE_SUPER_ADMIN%');

        return $qb->getQuery()->getResult();
    }
}
