<?php

namespace TIC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientAddressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAddressesRepository extends EntityRepository
{
    /**
     * @param Clients $client
     * @param $clientAddressID
     * @return ClientAddresses
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneWithAll(Clients $client, $clientAddressID)
    {
        $qb = $this->createQueryBuilder('ca')
            ->leftJoin('ca.address', 'a')
            ->addSelect('a')
            ->where('ca.client = :client')
            ->andWhere('ca.id = :clientAddressID')
            ->setParameters(array(
                'client' => $client,
                'clientAddressID' => $clientAddressID
            ));

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $clientID
     * @param $clientAddressID
     * @return ClientAddresses
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($clientID, $clientAddressID)
    {
        $qb = $this->createQueryBuilder('ca')
            ->leftJoin('ca.client', 'c')
            ->leftJoin('ca.address', 'a')
            ->addSelect('a')
            ->leftJoin('a.sessions', 's')
            ->addSelect('s')
            ->where('ca.id = :clientAddressID')
            ->andWhere('c.id = :clientID')
            ->setParameters(array(
                'clientID' => $clientID,
                'clientAddressID' => $clientAddressID
            ));

        return $qb->getQuery()->getOneOrNullResult();
    }
}
