<?php

namespace TIC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientsCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsCategoriesRepository extends EntityRepository
{
    /**
     * @return ClientsCategories[]
     */
    public function findAllWithRequiredData()
    {
        $qb = $this->createQueryBuilder('cc');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $itemID
     * @return ClientsCategories
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneWithRequiredData($itemID)
    {
        $qb = $this->createQueryBuilder('cc')
            ->where('cc.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $itemID
     * @return ClientsCategories
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($itemID)
    {
        $qb = $this->createQueryBuilder('cc')
            ->leftJoin('cc.clients', 'c')
            ->addSelect('c')
            ->where('cc.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
