<?php

namespace TIC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactPeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPeopleRepository extends EntityRepository
{
    /**
     * @param Clients $client
     * @param $contactPeopleID
     * @return ContactPeople
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneWithAll(Clients $client, $contactPeopleID)
    {
        $qb= $this->createQueryBuilder('cp')
            ->leftJoin('cp.address', 'a')
            ->addSelect('a')
            ->where('cp.id = :contactPeopleID')
            ->andWhere('cp.client = :client')
            ->setParameters(array(
                'client' => $client,
                'contactPeopleID' => $contactPeopleID
            ));

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $clientID
     * @param $contactPeopleID
     * @return ContactPeople
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($clientID, $contactPeopleID)
    {
        $qb = $this->createQueryBuilder('cp')
            ->leftJoin('cp.client', 'c')
            ->leftJoin('cp.address', 'a')
            ->addSelect('a')
            ->leftJoin('a.sessions', 's')
            ->addSelect('s')
            ->where('cp.id = :contactPeopleID')
            ->andWhere('c.id = :clientID')
            ->setParameters(array(
                'clientID' => $clientID,
                'contactPeopleID' => $contactPeopleID
            ));

        return $qb->getQuery()->getOneOrNullResult();
    }
}
