<?php

namespace TIC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountriesRepository extends EntityRepository
{
    /**
     * @return Countries[]
     */
    public function findAllWithRequiredData()
    {
        $qb = $this->createQueryBuilder('c');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $itemID
     * @return Countries
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneWithRequiredData($itemID)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $itemID
     * @return Countries
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($itemID)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.addresses', 'a')
            ->addSelect('a')
            ->leftJoin('c.trainers', 't')
            ->addSelect('t')
            ->where('c.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
