<?php

namespace TIC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesRepository extends EntityRepository
{
    /**
     * @return Languages[]
     */
    public function findAllWithRequiredData()
    {
        $qb = $this->createQueryBuilder('l');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $itemID
     * @return Languages
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneWithRequiredData($itemID)
    {
        $qb = $this->createQueryBuilder('l')
            ->where('l.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $itemID
     * @return Languages
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($itemID)
    {
        $qb = $this->createQueryBuilder('l')
            ->leftJoin('l.sessions', 's')
            ->addSelect('s')
            ->leftJoin('l.trainers', 't')
            ->addSelect('t')
            ->where('l.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
