<?php

namespace TIC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ToolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolsRepository extends EntityRepository
{
    /**
     * @return Tools[]
     */
    public function findAllWithRequiredData()
    {
        $qb = $this->createQueryBuilder('t');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $itemID
     * @return Tools
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneWithRequiredData($itemID)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $itemID
     * @return Tools
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($itemID)
    {
        $qb = $this->createQueryBuilder('t')
            ->leftJoin('t.trainings', 'tt')
            ->addSelect('tt')
            ->where('t.id = :itemID')
            ->setParameter('itemID', $itemID);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllFilteredQuery()
    {
        $qb = $this->createQueryBuilder('t')
            ->orderBy('t.toolName', 'ASC');

        return $qb;
    }
}
