<?php

namespace TIC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingsRepository extends EntityRepository
{
    /**
     * @return Trainings[]
     */
    public function findAllWithAll()
    {
        $qb = $this->createQueryBuilder('t')
        ->leftJoin('t.tools', 'to')
        ->addSelect('to');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $trainingID
     * @return Trainings
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findForDelete($trainingID)
    {
        $qb = $this->createQueryBuilder('t')
            ->leftJoin('t.sessions', 's')
            ->addSelect('s')
            ->where('t.id = :trainingID')
            ->setParameter('trainingID', $trainingID);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllActiveQuery()
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.trainingActive = TRUE');

        return $qb;
    }
}
