tic_platform_main_dispatch:
    path:   /
    defaults:
        _controller: TICPlatformBundle:Main:dispach
    methods: [ GET ]

tic_platform:
    resource: "@TICPlatformBundle/Resources/config/routing.yml"

# SECURITY ROUTES
fos_user_security_login:
   path: /login
   defaults: {_controller: FOSUserBundle:Security:login}

fos_user_security_check:
   path: /login_check
   defaults: {_controller: FOSUserBundle:Security:check}

fos_user_security_logout:
   path: /logout
   defaults: {_controller: FOSUserBundle:Security:logout}

# RESETTING ROUTES
fos_user_resetting_request:
   path: /request
   defaults: {_controller: FOSUserBundle:Resetting:request}

fos_user_resetting_send_email:
   path: /send-email
   defaults: {_controller: FOSUserBundle:Resetting:sendEmail}

fos_user_resetting_check_email:
   path: /check-email
   defaults: {_controller: FOSUserBundle:Resetting:checkEmail}

fos_user_resetting_reset:
   path: /reset/{token}
   defaults: {_controller: FOSUserBundle:Resetting:reset}

# CHANGE PASSWORD ROUTE
fos_user_change_password:
   path: /change-password
   defaults: {_controller: FOSUserBundle:ChangePassword:changePassword}

# Profile
fos_user_profile_show:
    path:     /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"